// <auto-generated />
namespace ZenithSociety.Migrations.Zenith
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstLastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstLastName));
        
        string IMigrationMetadata.Id
        {
            get { return "201610120825509_FirstLastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
